# Generated by Django 3.0.3 on 2020-02-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questapp', '0002_places_clue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
