# Generated by Django 3.0.3 on 2020-02-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questapp', '0003_auto_20200229_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='clue',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
